version: '2.1'

services:
  terraform:
    image: "${DOCKER_HUB:-}${DOCKER_IMAGE_NAME:-terraform-skeleton}:${DOCKER_IMAGE_TAG:-latest}"
    build:
      context: .
      args:
        TERRAFORM_IMAGE_NAME: "${TERRAFORM_IMAGE_NAME}"
        TERRAFORM_IMAGE_TAG: "${TERRAFORM_IMAGE_TAG}"
        AZURE_CLI_VERSION: "${AZURE_CLI_VERSION}"
    working_dir: /workspace/manifests
    volumes:
      - .:/workspace
    environment:
      ARM_CLIENT_ID: "${ARM_CLIENT_ID:-}"
      ARM_CLIENT_SECRET: "${ARM_CLIENT_SECRET:-}"
      ARM_SUBSCRIPTION_ID: "${ARM_SUBSCRIPTION_ID}"
      ARM_TENANT_ID: "${ARM_TENANT_ID}"
      ARM_ACCESS_KEY: "${TERRAFORM_STORAGE_ACCOUNT_ACCESS_KEY}"
      TF_VAR_terraform_storage_account_name: "${TERRAFORM_STORAGE_ACCOUNT_NAME}"
      TF_VAR_terraform_resource_group_name: "${TERRAFORM_RESOURCE_GROUP_NAME}"
      TF_VAR_environment: "${ENVIRONMENT}"
      TF_VAR_location: "${ARM_LOCATION}"

  terraform-init:
    extends: terraform
    entrypoint: []
    command: ../bin/terraform-init.sh